#!/usr/bin/env python3
"""Generate PDF audit report for Pune Neuro Society website."""

from fpdf import FPDF
from datetime import date


class AuditReport(FPDF):
    def header(self):
        if self.page_no() > 1:
            self.set_font("Helvetica", "I", 8)
            self.set_text_color(120, 120, 120)
            self.cell(0, 8, "Pune Neuro Society - Website Audit Report", align="L")
            self.cell(0, 8, f"Page {self.page_no()}/{{nb}}", align="R", new_x="LMARGIN", new_y="NEXT")
            self.line(10, 16, 200, 16)
            self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, "Generated by Claude Code | Confidential", align="C")

    def section_title(self, title, r=30, g=60, b=120):
        self.set_font("Helvetica", "B", 13)
        self.set_text_color(r, g, b)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(r, g, b)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def sub_title(self, title):
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(50, 50, 50)
        self.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
        self.ln(1)

    def body_text(self, text):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 5, text)
        self.ln(2)

    def badge(self, text, r, g, b):
        self.set_font("Helvetica", "B", 8)
        self.set_fill_color(r, g, b)
        self.set_text_color(255, 255, 255)
        w = self.get_string_width(text) + 6
        self.cell(w, 5.5, text, fill=True)
        self.set_text_color(40, 40, 40)

    def issue_row(self, issue_id, severity, title, file, status):
        y_start = self.get_y()
        if y_start > 260:
            self.add_page()
            y_start = self.get_y()

        self.set_font("Helvetica", "B", 8)
        self.set_text_color(40, 40, 40)
        self.cell(14, 6, issue_id)

        colors = {
            "CRITICAL": (200, 30, 30),
            "HIGH": (220, 120, 0),
            "MEDIUM": (50, 130, 180),
        }
        r, g, b = colors.get(severity, (100, 100, 100))
        self.badge(severity, r, g, b)
        self.cell(2, 6, "")

        self.set_font("Helvetica", "", 8)
        self.set_text_color(40, 40, 40)
        x_title = self.get_x()
        self.cell(75, 6, title[:55])

        self.set_font("Courier", "", 7)
        self.set_text_color(100, 100, 100)
        self.cell(40, 6, file[:30])

        if status == "FIXED":
            self.badge("FIXED", 40, 160, 60)
        else:
            self.badge("OPEN", 180, 80, 40)
        self.ln(7)


def build_report():
    pdf = AuditReport()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)

    # ── Page 1: Cover ──
    pdf.add_page()
    pdf.ln(30)
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(30, 60, 120)
    pdf.cell(0, 14, "Website Audit Report", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)
    pdf.set_font("Helvetica", "", 16)
    pdf.set_text_color(80, 80, 80)
    pdf.cell(0, 10, "Neurological Society of Pune", align="C", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)
    pdf.set_draw_color(30, 60, 120)
    pdf.line(60, pdf.get_y(), 150, pdf.get_y())
    pdf.ln(10)

    meta = [
        ("Date", "April 1, 2026"),
        ("Scope", "6 HTML pages, 1 JS, CSS/assets"),
        ("Branch", "claude/audit-website-errors-AqVFF"),
        ("Auditor", "Claude Code (Automated)"),
        ("Total Issues", "29 (16 code + 13 spelling/grammar)"),
        ("Fixed", "24"),
        ("Remaining", "5 (need owner input)"),
    ]
    pdf.set_font("Helvetica", "", 10)
    for label, value in meta:
        pdf.set_text_color(100, 100, 100)
        pdf.cell(50, 7, label + ":", align="R")
        pdf.cell(5, 7, "")
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)

    pdf.ln(15)
    # Summary box
    pdf.set_fill_color(240, 245, 255)
    pdf.set_draw_color(30, 60, 120)
    y = pdf.get_y()
    pdf.rect(15, y, 180, 30, style="DF")
    pdf.set_xy(20, y + 4)
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(30, 60, 120)
    pdf.cell(0, 6, "Executive Summary")
    pdf.set_xy(20, y + 12)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(170, 5,
        "The audit identified 29 issues across 6 HTML pages, 1 JavaScript file, and supporting assets. "
        "Critical issues included a JavaScript null-reference crash halting all interactivity, a non-existent "
        "Font Awesome CDN (v7.0.1), template placeholder data visible to end users, and 13 spelling/grammar "
        "mistakes. 24 of 29 issues have been fixed; 5 require content from the site owner."
    )

    # ── Page 2: Severity Breakdown ──
    pdf.add_page()
    pdf.section_title("1. Issue Severity Breakdown")

    headers = ["Severity", "Count", "Fixed", "Open"]
    widths = [40, 30, 30, 30]
    data = [
        ("Critical", "5", "5", "0"),
        ("High", "5", "4", "1"),
        ("Medium", "6", "2", "4"),
        ("Spelling/Grammar", "13", "13", "0"),
        ("TOTAL", "29", "24", "5"),
    ]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(30, 60, 120)
    pdf.set_text_color(255, 255, 255)
    for i, h in enumerate(headers):
        pdf.cell(widths[i], 7, h, border=1, fill=True, align="C")
    pdf.ln()
    pdf.set_text_color(40, 40, 40)
    for row in data:
        bold = row[0] == "TOTAL"
        pdf.set_font("Helvetica", "B" if bold else "", 9)
        if bold:
            pdf.set_fill_color(230, 235, 245)
        else:
            pdf.set_fill_color(255, 255, 255)
        for i, val in enumerate(row):
            pdf.cell(widths[i], 7, val, border=1, fill=True, align="C" if i > 0 else "L")
        pdf.ln()

    pdf.ln(6)
    pdf.section_title("2. Technology Stack")
    pdf.body_text(
        "Framework: Bootstrap 5.3.3 | jQuery 3.7.1\n"
        "Plugins: Slick Slider, Magnific Popup, Nice Select, AOS (Animate on Scroll)\n"
        "Icons: Font Awesome 6.5.1 (CDN) + Flaticon (local)\n"
        "Fonts: DM Sans (Google Fonts)\n"
        "Pages: index.html, about.html, activities.html, contact.html, committe.html, invited_faculties.html"
    )

    # ── Page 3: Critical Issues ──
    pdf.add_page()
    pdf.section_title("3. Critical Issues", 200, 30, 30)

    critical = [
        ("C-01", "JavaScript null-reference crash on progressPath",
         "main.js:57-58", "FIXED",
         "document.querySelector('.progress-wrap path') returns null on every page because no "
         ".progress-wrap element exists in any HTML file. This uncaught TypeError halts ALL subsequent "
         "JavaScript execution, breaking sliders, animations, counters, and scroll effects.\n"
         "Fix: Wrapped in null guard (if statement)."),
        ("C-02", "Font Awesome CDN returns 404 (v7.0.1 does not exist)",
         "All 6 HTML files", "FIXED",
         "All pages load font-awesome/7.0.1/css/all.min.css from cdnjs. Font Awesome v7 does not exist "
         "on cdnjs; the latest is 6.x. This returns a 404 error, so all <i class='fa-*'> icons are invisible.\n"
         "Fix: Changed to v6.5.1 with correct SRI integrity hash."),
        ("C-03", "Template placeholder data visible to users",
         "index.html (mobile menu)", "FIXED",
         "The mobile off-canvas menu displays the original template's dummy data: phone +57 9954 6476, "
         "email hello@exdos.com, address 'Bhemeara, Kushtia'. Additionally, the envelope icon was "
         "paired with the phone number and vice versa (swapped).\n"
         "Fix: Replaced with NSP's real contact info and corrected icon assignments."),
        ("C-04", "Footer shows 'Contact details to be updated'",
         "All 6 HTML files", "FIXED",
         "Every page footer displays the literal text 'Contact details to be updated' as a visible "
         "placeholder that end users can see.\n"
         "Fix: Replaced with info@neurologicalsocietyofpune.com."),
        ("C-05", "Wrong <title> tag on Activities page",
         "activities.html", "FIXED",
         "The <title> says 'About Us - Neurological Society of Pune' instead of 'Activities'.\n"
         "Fix: Changed to 'Activities - Neurological Society of Pune'."),
    ]

    for cid, title, file, status, desc in critical:
        if pdf.get_y() > 240:
            pdf.add_page()
        pdf.issue_row(cid, "CRITICAL", title, file, status)
        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(182, 4.5, desc)
        pdf.ln(4)

    # ── High Priority Issues ──
    pdf.add_page()
    pdf.section_title("4. High Priority Issues", 220, 120, 0)

    high = [
        ("H-01", "Broken internal links (4 pages don't exist)",
         "index.html", "FIXED",
         "Links to team.html (6 refs), projects-single.html (4 refs), and blog-single.html (5 refs) "
         "all lead to 404 errors.\n"
         "Fix: Redirected to invited_faculties.html and activities.html respectively."),
        ("H-02", "Missing AOS.init() call",
         "committe.html, invited_faculties.html", "FIXED",
         "AOS library is loaded but AOS.init() is never called, so scroll-triggered animations "
         "don't work on these two pages.\nFix: Added AOS.init() call before closing </body>."),
        ("H-03", "Inconsistent mobile menu logo",
         "committe.html, invited_faculties.html", "FIXED",
         "These two pages use logo1.png while the other 4 pages use '21 Logo.png'.\n"
         "Fix: Standardized to '21 Logo.png'."),
        ("H-04", "Swapped prev/next arrow selectors in Slick sliders",
         "main.js (5 instances)", "FIXED",
         "prevArrow pointed to .next-arrow and nextArrow pointed to .prev-arrow in 5 slider configs.\n"
         "Fix: Corrected all 5 selector assignments."),
        ("H-05", "Committee page shows faculty data instead of committee members",
         "committe.html", "OPEN",
         "The committee page displays the exact same faculty cards as invited_faculties.html. "
         "It needs real committee/office-bearer data from the organization.\n"
         "Status: Requires content from site owner."),
    ]

    for hid, title, file, status, desc in high:
        if pdf.get_y() > 240:
            pdf.add_page()
        pdf.issue_row(hid, "HIGH", title, file, status)
        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(182, 4.5, desc)
        pdf.ln(4)

    # ── Medium Priority Issues ──
    pdf.add_page()
    pdf.section_title("5. Medium Priority Issues", 50, 130, 180)

    medium = [
        ("M-01", "Contact form accessibility issues",
         "contact.html", "FIXED",
         "Form inputs lacked <label>, name, id, and aria-required attributes.\n"
         "Fix: Added proper label/id/name/aria-required to all form fields."),
        ("M-02", "Footer Bootstrap grid broken (col outside row)",
         "All 6 HTML files", "FIXED",
         "A col-lg-12 div was placed outside its parent row div.\n"
         "Fix: Wrapped in proper row container."),
        ("M-03", "All social media links are placeholder href='#'",
         "All 6 HTML files", "OPEN",
         "Facebook, LinkedIn, Instagram, YouTube links go nowhere. Need real URLs."),
        ("M-04", "All images have empty alt='' attributes",
         "All 6 HTML files", "OPEN",
         "No descriptive alt text on any image. Poor for accessibility and SEO."),
        ("M-05", "Image filename typos and spaces",
         "assets/img/", "OPEN",
         "preloder.png (should be preloader), conerence-talk.png (conference), "
         "'21 Logo.png' has a space. Renaming requires updating all references."),
        ("M-06", "Duplicate meta descriptions across pages",
         "All 6 HTML files", "OPEN",
         "Multiple pages share the same meta description text. Bad for SEO."),
    ]

    for mid, title, file, status, desc in medium:
        if pdf.get_y() > 245:
            pdf.add_page()
        pdf.issue_row(mid, "MEDIUM", title, file, status)
        pdf.set_x(14)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(182, 4.5, desc)
        pdf.ln(4)

    # ── Spelling & Grammar Section ──
    pdf.add_page()
    pdf.section_title("6. Spelling & Grammar Issues (13 Found, All Fixed)", 140, 50, 140)

    pdf.body_text(
        "A thorough text review of all HTML pages identified 13 spelling, grammar, and factual errors. "
        "All have been corrected in the codebase."
    )

    sg_issues = [
        ("SG-01", "Nuero -> Neuro", "index.html", "FIXED",
         "Misspelling of 'Neuro' as 'Nuero' in the hero section heading."),
        ("SG-02", "Nurological -> Neurological", "index.html", "FIXED",
         "Misspelling of 'Neurological' as 'Nurological' in hero subtitle."),
        ("SG-03", "reserch -> research", "index.html", "FIXED",
         "Misspelling of 'research' in the about section description text."),
        ("SG-04", "strength -> strengthen", "index.html", "FIXED",
         "Wrong word form: 'strength' used as a verb instead of 'strengthen'."),
        ("SG-05", "nuroscience -> neuroscience", "index.html", "FIXED",
         "Misspelling of 'neuroscience' in mission description."),
        ("SG-06", "diseses -> diseases", "index.html", "FIXED",
         "Misspelling of 'diseases' in the activities section."),
        ("SG-07", "nuero -> neuro", "index.html", "FIXED",
         "Lowercase misspelling of 'neuro' in body text."),
        ("SG-08", "Terms Of Condition -> Terms and Conditions", "All 6 files", "FIXED",
         "Incorrect phrase 'Terms Of Condition' in footer quick links across all pages."),
        ("SG-09", "Last but not the least -> Last but not least", "activities.html", "FIXED",
         "Common grammar error: unnecessary article 'the' in the idiom."),
        ("SG-10", "strength -> strengthen", "activities.html", "FIXED",
         "Same verb-form error as SG-04, repeated on the activities page."),
        ("SG-11", "nuroscience -> neuroscience", "activities.html", "FIXED",
         "Same misspelling as SG-05, repeated on the activities page."),
        ("SG-12", "Philadelphia (Harvard reference)", "activities.html", "FIXED",
         "Text says 'Harvard University, Philadelphia' - Harvard is in Cambridge/Boston, MA. "
         "Changed to 'Harvard University, Boston'."),
        ("SG-13", "Explore Our Key Activites -> Activities", "index.html, activities.html", "FIXED",
         "Misspelling of 'Activities' as 'Activites' in section headings."),
    ]

    # Table header
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(140, 50, 140)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(14, 6, "ID", border=1, fill=True, align="C")
    pdf.cell(50, 6, "Error -> Fix", border=1, fill=True, align="C")
    pdf.cell(40, 6, "File(s)", border=1, fill=True, align="C")
    pdf.cell(14, 6, "Status", border=1, fill=True, align="C")
    pdf.cell(72, 6, "Description", border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_text_color(40, 40, 40)
    for i, (sid, title, file, status, desc) in enumerate(sg_issues):
        if pdf.get_y() > 260:
            pdf.add_page()
        bg = (250, 245, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)

        y_before = pdf.get_y()
        x_start = pdf.get_x()

        pdf.set_font("Helvetica", "B", 7)
        pdf.cell(14, 6, sid, border=1, fill=True, align="C")
        pdf.set_font("Helvetica", "", 7)
        pdf.cell(50, 6, title[:35], border=1, fill=True)
        pdf.set_font("Courier", "", 6)
        pdf.cell(40, 6, file[:28], border=1, fill=True)

        pdf.set_font("Helvetica", "B", 7)
        if status == "FIXED":
            pdf.set_text_color(40, 160, 60)
        else:
            pdf.set_text_color(180, 80, 40)
        pdf.cell(14, 6, status, border=1, fill=True, align="C")
        pdf.set_text_color(40, 40, 40)

        pdf.set_font("Helvetica", "", 6.5)
        pdf.cell(72, 6, desc[:52], border=1, fill=True)
        pdf.ln()

    # ── JavaScript Audit Details ──
    pdf.add_page()
    pdf.section_title("7. JavaScript Audit Details (main.js)")

    js_issues = [
        ("Line 57-58", "CRITICAL", "progressPath null crash", "FIXED"),
        ("Line 6-16", "HIGH", "Swapped prev/next in testi slider", "FIXED"),
        ("Line 20-30", "HIGH", "Swapped prev/next in testi2 slider", "FIXED"),
        ("Line 35-45", "HIGH", "Swapped prev/next in testi3 slider", "FIXED"),
        ("Line 70-80", "HIGH", "Swapped prev/next in blog slider", "FIXED"),
        ("Line 85-95", "HIGH", "Swapped prev/next in brand slider", "FIXED"),
        ("Line 106", "MEDIUM", "AOS.init; (statement, not call)", "FIXED"),
        ("Line 108+", "LOW", "Counter code outside IIFE scope", "INFO"),
        ("Line 60-65", "LOW", "Unused scroll offset variable", "INFO"),
    ]

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(30, 60, 120)
    pdf.set_text_color(255, 255, 255)
    for h, w in [("Location", 28), ("Severity", 22), ("Issue", 85), ("Status", 18)]:
        pdf.cell(w, 6, h, border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_text_color(40, 40, 40)
    for i, (loc, sev, issue, status) in enumerate(js_issues):
        bg = (240, 245, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_font("Courier", "", 7)
        pdf.cell(28, 6, loc, border=1, fill=True)
        # severity color
        sev_colors = {"CRITICAL": (200, 30, 30), "HIGH": (220, 120, 0), "MEDIUM": (50, 130, 180), "LOW": (120, 120, 120)}
        r, g, b = sev_colors.get(sev, (100, 100, 100))
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_text_color(r, g, b)
        pdf.cell(22, 6, sev, border=1, fill=True, align="C")
        pdf.set_text_color(40, 40, 40)
        pdf.set_font("Helvetica", "", 7)
        pdf.cell(85, 6, issue, border=1, fill=True)
        pdf.set_font("Helvetica", "B", 7)
        if status == "FIXED":
            pdf.set_text_color(40, 160, 60)
        else:
            pdf.set_text_color(100, 100, 100)
        pdf.cell(18, 6, status, border=1, fill=True, align="C")
        pdf.set_text_color(40, 40, 40)
        pdf.ln()

    # ── Files Modified ──
    pdf.ln(8)
    pdf.section_title("8. Files Modified")

    files_modified = [
        ("assets/js/main.js", "Null crash fix, arrow swap fix, AOS.init fix"),
        ("index.html", "FA CDN, mobile menu data, broken links, footer, spelling (7 fixes)"),
        ("about.html", "FA CDN, footer placeholder, terms grammar"),
        ("activities.html", "FA CDN, title tag, footer, terms, spelling (5 fixes)"),
        ("contact.html", "FA CDN, footer, form accessibility, terms"),
        ("committe.html", "FA CDN, AOS.init, logo, footer grid, terms"),
        ("invited_faculties.html", "FA CDN, AOS.init, logo, footer grid, terms"),
    ]

    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(30, 60, 120)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(55, 6, "File", border=1, fill=True)
    pdf.cell(135, 6, "Changes", border=1, fill=True)
    pdf.ln()

    pdf.set_text_color(40, 40, 40)
    for i, (f, changes) in enumerate(files_modified):
        bg = (240, 245, 255) if i % 2 == 0 else (255, 255, 255)
        pdf.set_fill_color(*bg)
        pdf.set_font("Courier", "", 7)
        pdf.cell(55, 6, f, border=1, fill=True)
        pdf.set_font("Helvetica", "", 7)
        pdf.cell(135, 6, changes, border=1, fill=True)
        pdf.ln()

    # ── Recommendations ──
    pdf.ln(8)
    pdf.section_title("9. Recommendations")

    recs = [
        "1. Provide real social media URLs for Facebook, LinkedIn, Instagram, YouTube links.",
        "2. Add real committee/office-bearer data to committe.html (currently shows faculty data).",
        "3. Add descriptive alt text to all images for accessibility and SEO compliance.",
        "4. Rename committe.html to committee.html and update all internal links.",
        "5. Rename image files: preloder.png -> preloader.png, conerence-talk.png -> conference-talk.png.",
        "6. Remove space from '21 Logo.png' filename (rename to nsp-logo.png or similar).",
        "7. Write unique <meta description> content for each page to improve SEO.",
        "8. Set up a form backend (Formspree, Netlify Forms, etc.) for the contact form.",
        "9. Add SSL certificate and enforce HTTPS for the production site.",
        "10. Consider adding a favicon (currently missing).",
    ]
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(40, 40, 40)
    for rec in recs:
        if pdf.get_y() > 270:
            pdf.add_page()
        pdf.multi_cell(0, 5, rec)
        pdf.ln(1)

    # Save
    pdf.output("/home/user/Pune-Neuro-Society/Website_Audit_Report.pdf")
    print("PDF generated: Website_Audit_Report.pdf")
    print(f"Pages: {pdf.page_no()}")


if __name__ == "__main__":
    build_report()
